#!/usr/bin/env bash
set -e

# Same normalisation as coder-login: _REMOTE_USER may arrive as a login name,
# a bare uid, or a "uid:gid" pair (docker-compose `user: "1000:1000"`).
: "${_REMOTE_USER:?claude-remote-control: _REMOTE_USER is not set}"
: "${_REMOTE_USER_HOME:?claude-remote-control: _REMOTE_USER_HOME is not set}"

_REMOTE_USER_ID="${_REMOTE_USER%%:*}"
_REMOTE_GROUP_ID=""
if [[ "$_REMOTE_USER" == *:* ]]; then
    _REMOTE_GROUP_ID="${_REMOTE_USER##*:}"
fi

_REMOTE_USER_NAME=""
if _remote_user_passwd="$(getent passwd "$_REMOTE_USER_ID" 2>/dev/null)"; then
    IFS=':' read -r _remote_name _ _ _remote_gid _ <<<"$_remote_user_passwd"
    _REMOTE_USER_NAME="$_remote_name"
    if [[ -z "$_REMOTE_GROUP_ID" ]]; then
        _REMOTE_GROUP_ID="$_remote_gid"
    fi
    unset _remote_name _remote_gid
fi

_REMOTE_USER_OWNER="${_REMOTE_USER_ID}${_REMOTE_GROUP_ID:+:${_REMOTE_GROUP_ID}}"

# Must match containerEnv / mounts in devcontainer-feature.json.
CLAUDE_CONFIG_DIR=/claude-config
SHARE_DIR=/usr/local/share/claude-remote-control

apt_install() {
    if ! command -v apt-get >/dev/null 2>&1; then
        echo "claude-remote-control: '$*' is missing and apt-get is unavailable; install it in the base image." >&2
        exit 1
    fi
    export DEBIAN_FRONTEND=noninteractive
    apt-get update -y
    apt-get install -y --no-install-recommends "$@"
    rm -rf /var/lib/apt/lists/*
}

missing=()
command -v tmux >/dev/null 2>&1 || missing+=(tmux)
command -v curl >/dev/null 2>&1 || missing+=(curl ca-certificates)
if [[ ${#missing[@]} -gt 0 ]]; then
    apt_install "${missing[@]}"
fi

# Docker seeds an empty named volume from the image, ownership included, so
# creating the directory here is what makes the volume writable by the remote
# user on first mount.
mkdir -p "$CLAUDE_CONFIG_DIR"
chown "$_REMOTE_USER_OWNER" "$CLAUDE_CONFIG_DIR"
chmod 700 "$CLAUDE_CONFIG_DIR"

if [[ "$INSTALLCLAUDE" == "true" ]] && ! command -v claude >/dev/null 2>&1; then
    if [[ -z "$_REMOTE_USER_NAME" ]]; then
        echo "claude-remote-control: no passwd entry for uid '$_REMOTE_USER_ID'; cannot install Claude Code as the remote user." >&2
        exit 1
    fi
    # The native installer puts claude under the user's ~/.local and keeps it
    # auto-updating there, so it has to run as that user, not as root.
    su "$_REMOTE_USER_NAME" -c "CLAUDE_CONFIG_DIR=$CLAUDE_CONFIG_DIR bash -c 'curl -fsSL https://claude.ai/install.sh | bash'"
    # ~/.local/bin is not on PATH for every shell or lifecycle hook. The link
    # follows the installer's own symlink, so auto-updates keep working.
    ln -sf "${_REMOTE_USER_HOME}/.local/bin/claude" /usr/local/bin/claude
fi

mkdir -p "$SHARE_DIR"
{
    echo '# Generated by the claude-remote-control dev container feature. Do not edit.'
    printf 'RC_SESSION_NAME=%q\n' "$SESSIONNAME"
    printf 'RC_PERMISSION_MODE=%q\n' "$PERMISSIONMODE"
    printf 'RC_SPAWN=%q\n' "$SPAWN"
} > "$SHARE_DIR/options.env"
chmod 0644 "$SHARE_DIR/options.env"

install -m 0755 "$(dirname "$0")/start.sh" "$SHARE_DIR/start.sh"
