#!/bin/bash
# The default (autogenerated) test runs as root, where `coder login` writing
# into root's home looks correct. Only a scenario with an explicit non-root
# remoteUser can reproduce the bug this test exists for.
set -e

source dev-container-features-test-lib

# The bug: install.sh ran `coder login` as root, so $CODER_CONFIG_DIR resolved
# to /root/.config/coderv2 and the remote user's `coder whoami` reported
# "signed out".
check "config dir exists in the remote user's home" test -d "$HOME/.config/coderv2"
check "config dir belongs to the remote user" bash -c '
  [ "$(stat -c %U "$HOME/.config/coderv2")" = "$(id -un)" ]
'
check "config dir is private" bash -c '
  [ "$(stat -c %a "$HOME/.config/coderv2")" = "700" ]
'
check "nothing left behind in root's home" bash -c '! sudo test -e /root/.config/coderv2'

# Regression test for the 2026-09-08 incident, held under the same scenario.
check "no credential assignment baked in" bash -c '
  ! grep -qE "^(export )?(CODER_AGENT_TOKEN|CODER_SESSION_TOKEN|CODER_AGENT_AUTH)=" \
      /etc/profile.d/coder-env.sh /etc/environment
'
check "no UUID-shaped secret baked in" bash -c '
  ! grep -qE "[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}" \
      /etc/profile.d/coder-env.sh /etc/environment /etc/bash.bashrc
'
check "agent token resolved at runtime" grep -q '/proc/' /usr/local/lib/coder-login/agent-env.sh
check "env file sources the resolver" grep -qF '/usr/local/lib/coder-login/agent-env.sh' /etc/profile.d/coder-env.sh

reportResults
